<?php

namespace ContainerLxkf2zO;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_N2aYfROService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.N2aYfRO' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.N2aYfRO'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.zHyJIs5.kernel::registerContainerConfiguration()', 'get_ServiceLocator_ZHyJIs5_KernelregisterContainerConfigurationService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.zHyJIs5.kernel::registerContainerConfiguration()', 'get_ServiceLocator_ZHyJIs5_KernelregisterContainerConfigurationService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.zHyJIs5.kernel::loadRoutes()', 'get_ServiceLocator_ZHyJIs5_KernelloadRoutesService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.zHyJIs5.kernel::loadRoutes()', 'get_ServiceLocator_ZHyJIs5_KernelloadRoutesService', true],
            'App\\Controller\\DashboardController::index' => ['privates', '.service_locator.dOCD7oY.App\\Controller\\DashboardController::index()', 'getDashboardControllerindexService', true],
            'App\\Controller\\DepotController::index' => ['privates', '.service_locator.Ka_jUWQ.App\\Controller\\DepotController::index()', 'getDepotControllerindexService', true],
            'App\\Controller\\DepotController::new' => ['privates', '.service_locator.egipcEH.App\\Controller\\DepotController::new()', 'getDepotControllernewService', true],
            'App\\Controller\\DepotController::show' => ['privates', '.service_locator.QAy5MA5.App\\Controller\\DepotController::show()', 'getDepotControllershowService', true],
            'App\\Controller\\DepotController::edit' => ['privates', '.service_locator.YIF0RGH.App\\Controller\\DepotController::edit()', 'getDepotControllereditService', true],
            'App\\Controller\\DepotController::delete' => ['privates', '.service_locator.YIF0RGH.App\\Controller\\DepotController::delete()', 'getDepotControllerdeleteService', true],
            'App\\Controller\\PointCollecteController::index' => ['privates', '.service_locator.zGhMqhQ', 'get_ServiceLocator_ZGhMqhQService', true],
            'App\\Controller\\PointCollecteController::new' => ['privates', '.service_locator.egipcEH.App\\Controller\\PointCollecteController::new()', 'getPointCollecteControllernewService', true],
            'App\\Controller\\PointCollecteController::show' => ['privates', '.service_locator.ZMsmb2J.App\\Controller\\PointCollecteController::show()', 'getPointCollecteControllershowService', true],
            'App\\Controller\\PointCollecteController::edit' => ['privates', '.service_locator.xDhs2.z.App\\Controller\\PointCollecteController::edit()', 'getPointCollecteControllereditService', true],
            'App\\Controller\\PointCollecteController::delete' => ['privates', '.service_locator.xDhs2.z.App\\Controller\\PointCollecteController::delete()', 'getPointCollecteControllerdeleteService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.zHyJIs5.kernel::registerContainerConfiguration()', 'get_ServiceLocator_ZHyJIs5_KernelregisterContainerConfigurationService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.zHyJIs5.kernel::loadRoutes()', 'get_ServiceLocator_ZHyJIs5_KernelloadRoutesService', true],
            'App\\Controller\\DashboardController:index' => ['privates', '.service_locator.dOCD7oY.App\\Controller\\DashboardController::index()', 'getDashboardControllerindexService', true],
            'App\\Controller\\DepotController:index' => ['privates', '.service_locator.Ka_jUWQ.App\\Controller\\DepotController::index()', 'getDepotControllerindexService', true],
            'App\\Controller\\DepotController:new' => ['privates', '.service_locator.egipcEH.App\\Controller\\DepotController::new()', 'getDepotControllernewService', true],
            'App\\Controller\\DepotController:show' => ['privates', '.service_locator.QAy5MA5.App\\Controller\\DepotController::show()', 'getDepotControllershowService', true],
            'App\\Controller\\DepotController:edit' => ['privates', '.service_locator.YIF0RGH.App\\Controller\\DepotController::edit()', 'getDepotControllereditService', true],
            'App\\Controller\\DepotController:delete' => ['privates', '.service_locator.YIF0RGH.App\\Controller\\DepotController::delete()', 'getDepotControllerdeleteService', true],
            'App\\Controller\\PointCollecteController:index' => ['privates', '.service_locator.zGhMqhQ', 'get_ServiceLocator_ZGhMqhQService', true],
            'App\\Controller\\PointCollecteController:new' => ['privates', '.service_locator.egipcEH.App\\Controller\\PointCollecteController::new()', 'getPointCollecteControllernewService', true],
            'App\\Controller\\PointCollecteController:show' => ['privates', '.service_locator.ZMsmb2J.App\\Controller\\PointCollecteController::show()', 'getPointCollecteControllershowService', true],
            'App\\Controller\\PointCollecteController:edit' => ['privates', '.service_locator.xDhs2.z.App\\Controller\\PointCollecteController::edit()', 'getPointCollecteControllereditService', true],
            'App\\Controller\\PointCollecteController:delete' => ['privates', '.service_locator.xDhs2.z.App\\Controller\\PointCollecteController::delete()', 'getPointCollecteControllerdeleteService', true],
        ], [
            'kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Controller\\DashboardController::index' => '?',
            'App\\Controller\\DepotController::index' => '?',
            'App\\Controller\\DepotController::new' => '?',
            'App\\Controller\\DepotController::show' => '?',
            'App\\Controller\\DepotController::edit' => '?',
            'App\\Controller\\DepotController::delete' => '?',
            'App\\Controller\\PointCollecteController::index' => '?',
            'App\\Controller\\PointCollecteController::new' => '?',
            'App\\Controller\\PointCollecteController::show' => '?',
            'App\\Controller\\PointCollecteController::edit' => '?',
            'App\\Controller\\PointCollecteController::delete' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:loadRoutes' => '?',
            'App\\Controller\\DashboardController:index' => '?',
            'App\\Controller\\DepotController:index' => '?',
            'App\\Controller\\DepotController:new' => '?',
            'App\\Controller\\DepotController:show' => '?',
            'App\\Controller\\DepotController:edit' => '?',
            'App\\Controller\\DepotController:delete' => '?',
            'App\\Controller\\PointCollecteController:index' => '?',
            'App\\Controller\\PointCollecteController:new' => '?',
            'App\\Controller\\PointCollecteController:show' => '?',
            'App\\Controller\\PointCollecteController:edit' => '?',
            'App\\Controller\\PointCollecteController:delete' => '?',
        ]);
    }
}
