<?php

namespace ContainerLxkf2zO;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_ZGhMqhQService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.zGhMqhQ' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.zGhMqhQ'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'pointCollecteRepository' => ['privates', '.errored.hXAnRgz', NULL, 'Cannot determine controller argument for "App\\Controller\\PointCollecteController::index()": the $pointCollecteRepository argument is type-hinted with the non-existent class or interface: "App\\Repository\\PointCollecteRepository".'],
        ], [
            'pointCollecteRepository' => '?',
        ]);
    }
}
