<?php

namespace ContainerLxkf2zO;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Errored_HXAnRgzService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored.hXAnRgz' shared service.
     *
     * @return \App\Repository\PointCollecteRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot determine controller argument for "App\\Controller\\PointCollecteController::index()": the $pointCollecteRepository argument is type-hinted with the non-existent class or interface: "App\\Repository\\PointCollecteRepository".');
    }
}
