<?php

namespace ContainerLxkf2zO;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDepotControllershowService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.QAy5MA5.App\Controller\DepotController::show()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.QAy5MA5.App\\Controller\\DepotController::show()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'depot' => ['privates', '.errored..service_locator.QAy5MA5.App\\Entity\\Depot', NULL, 'Cannot autowire service ".service_locator.QAy5MA5": it needs an instance of "App\\Entity\\Depot" but this type has been excluded because it\'s a Doctrine entity.'],
        ], [
            'depot' => 'App\\Entity\\Depot',
        ]))->withContext('App\\Controller\\DepotController::show()', $container);
    }
}
