<?php

namespace ContainerLxkf2zO;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDashboardControllerindexService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.dOCD7oY.App\Controller\DashboardController::index()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.dOCD7oY.App\\Controller\\DashboardController::index()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'depotRepository' => ['privates', 'App\\Repository\\DepotRepository', 'getDepotRepositoryService', true],
            'pointCollecteRepository' => ['privates', '.errored.4_bw6VE', NULL, 'Cannot determine controller argument for "App\\Controller\\DashboardController::index()": the $pointCollecteRepository argument is type-hinted with the non-existent class or interface: "App\\Repository\\PointCollecteRepository".'],
        ], [
            'depotRepository' => 'App\\Repository\\DepotRepository',
            'pointCollecteRepository' => '?',
        ]))->withContext('App\\Controller\\DashboardController::index()', $container);
    }
}
