<?php

namespace ContainerLxkf2zO;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDepotControllerdeleteService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.YIF0RGH.App\Controller\DepotController::delete()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.YIF0RGH.App\\Controller\\DepotController::delete()'] = ($container->privates['.service_locator.YIF0RGH'] ?? $container->load('get_ServiceLocator_YIF0RGHService'))->withContext('App\\Controller\\DepotController::delete()', $container);
    }
}
