<?php

namespace ContainerLxkf2zO;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDepotControllereditService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.YIF0RGH.App\Controller\DepotController::edit()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['.service_locator.YIF0RGH'] ?? $container->load('get_ServiceLocator_YIF0RGHService'));

        if (isset($container->privates['.service_locator.YIF0RGH.App\\Controller\\DepotController::edit()'])) {
            return $container->privates['.service_locator.YIF0RGH.App\\Controller\\DepotController::edit()'];
        }

        return $container->privates['.service_locator.YIF0RGH.App\\Controller\\DepotController::edit()'] = $a->withContext('App\\Controller\\DepotController::edit()', $container);
    }
}
