<?php

namespace ContainerLxkf2zO;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPointCollecteTypeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Form\PointCollecteType' shared autowired service.
     *
     * @return \App\Form\PointCollecteType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/src/Form/PointCollecteType.php';

        return $container->privates['App\\Form\\PointCollecteType'] = new \App\Form\PointCollecteType();
    }
}
