<?php

namespace ContainerLxkf2zO;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPointCollecteControllerdeleteService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.xDhs2.z.App\Controller\PointCollecteController::delete()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.xDhs2.z.App\\Controller\\PointCollecteController::delete()'] = ($container->privates['.service_locator.xDhs2.z'] ?? $container->load('get_ServiceLocator_XDhs2_ZService'))->withContext('App\\Controller\\PointCollecteController::delete()', $container);
    }
}
