<?php

namespace ContainerLxkf2zO;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPointCollecteControllershowService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.ZMsmb2J.App\Controller\PointCollecteController::show()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.ZMsmb2J.App\\Controller\\PointCollecteController::show()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'pointCollecte' => ['privates', '.errored..service_locator.ZMsmb2J.App\\Entity\\PointCollecte', NULL, 'Cannot autowire service ".service_locator.ZMsmb2J": it needs an instance of "App\\Entity\\PointCollecte" but this type has been excluded because it\'s a Doctrine entity.'],
        ], [
            'pointCollecte' => 'App\\Entity\\PointCollecte',
        ]))->withContext('App\\Controller\\PointCollecteController::show()', $container);
    }
}
