<?php

namespace ContainerLxkf2zO;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPointCollecteService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.ZMsmb2J.App\Entity\PointCollecte' shared service.
     *
     * @return \App\Entity\PointCollecte
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.ZMsmb2J": it needs an instance of "App\\Entity\\PointCollecte" but this type has been excluded because it\'s a Doctrine entity.');
    }
}
