<?php

namespace ContainerLxkf2zO;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPointCollecteControllereditService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.xDhs2.z.App\Controller\PointCollecteController::edit()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['.service_locator.xDhs2.z'] ?? $container->load('get_ServiceLocator_XDhs2_ZService'));

        if (isset($container->privates['.service_locator.xDhs2.z.App\\Controller\\PointCollecteController::edit()'])) {
            return $container->privates['.service_locator.xDhs2.z.App\\Controller\\PointCollecteController::edit()'];
        }

        return $container->privates['.service_locator.xDhs2.z.App\\Controller\\PointCollecteController::edit()'] = $a->withContext('App\\Controller\\PointCollecteController::edit()', $container);
    }
}
