<?php

namespace ContainerCUc4tvD;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_XDhs2_ZService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.xDhs2.z' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.xDhs2.z'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'pointCollecte' => ['privates', '.errored..service_locator.xDhs2.z.App\\Entity\\PointCollecte', NULL, 'Cannot autowire service ".service_locator.xDhs2.z": it needs an instance of "App\\Entity\\PointCollecte" but this type has been excluded because it\'s a Doctrine entity.'],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'pointCollecte' => 'App\\Entity\\PointCollecte',
            'entityManager' => '?',
        ]);
    }
}
