<?php

namespace ContainerCUc4tvD;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDepotService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.QAy5MA5.App\Entity\Depot' shared service.
     *
     * @return \App\Entity\Depot
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.QAy5MA5": it needs an instance of "App\\Entity\\Depot" but this type has been excluded because it\'s a Doctrine entity.');
    }
}
