<?php

namespace ContainerCUc4tvD;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDepotControllerindexService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Ka_jUWQ.App\Controller\DepotController::index()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Ka_jUWQ.App\\Controller\\DepotController::index()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'depotRepository' => ['privates', 'App\\Repository\\DepotRepository', 'getDepotRepositoryService', true],
        ], [
            'depotRepository' => 'App\\Repository\\DepotRepository',
        ]))->withContext('App\\Controller\\DepotController::index()', $container);
    }
}
