<?php

namespace ContainerCUc4tvD;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDashboardControllerindexService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.exQZcwl.App\Controller\DashboardController::index()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.exQZcwl.App\\Controller\\DashboardController::index()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'depotRepository' => ['privates', 'App\\Repository\\DepotRepository', 'getDepotRepositoryService', true],
            'pointCollecteRepository' => ['privates', 'App\\Repository\\PointCollecteRepository', 'getPointCollecteRepositoryService', true],
        ], [
            'depotRepository' => 'App\\Repository\\DepotRepository',
            'pointCollecteRepository' => 'App\\Repository\\PointCollecteRepository',
        ]))->withContext('App\\Controller\\DashboardController::index()', $container);
    }
}
