<?php

namespace ContainerCUc4tvD;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPointCollecteControllerindexService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.JkRnisc.App\Controller\PointCollecteController::index()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.JkRnisc.App\\Controller\\PointCollecteController::index()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'pointCollecteRepository' => ['privates', 'App\\Repository\\PointCollecteRepository', 'getPointCollecteRepositoryService', true],
        ], [
            'pointCollecteRepository' => 'App\\Repository\\PointCollecteRepository',
        ]))->withContext('App\\Controller\\PointCollecteController::index()', $container);
    }
}
