<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerCUc4tvD\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerCUc4tvD/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerCUc4tvD.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerCUc4tvD\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerCUc4tvD\App_KernelDevDebugContainer([
    'container.build_hash' => 'CUc4tvD',
    'container.build_id' => '46821f3e',
    'container.build_time' => 1759760431,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerCUc4tvD');
